### ISSUE TITLE
请问输出结果results.txt文件的格式是什么？

### ISSUE THREAD

**Issue by HPDell** [zinkcious/MapMatching#1]
我根据代码猜测的格式是：

车辆ID，前一个轨迹点的时刻，当前轨迹点的时刻，该段轨迹覆盖的长度，该段轨迹所用的时间，输出geo要素

请问车辆轨迹点匹配到的路段是在那里指明的？实在最后一个字段中吗？

**Comment by zinkcious** [comment]
最后的字段是输出的匹配路段，包括每个路段的id以及车辆经过该路段的百分比

**Comment by HPDell** [comment]
明白了。谢谢
