### ISSUE TITLE
请问你解决下面的问题了吗？是什么原因导致的？谢谢

### ISSUE THREAD

**Issue by wuguangbin1230** [zinkcious/MapMatching#2]
But the tk1 has only one usb port, if I don't use a usbhub, I can't usb other usb devices such a laser.

And I tried what you said, don't use a usbhub, plug the usb port of kinect directly into the usb port on tk1 and remote control tk1. But I encounter new problems when I do this.

If I connect tk1 using ssh, and input ./bin/Protonect, it tells me following errors

[Info] [Freenect2Impl] enumerating devices...
[Info] [Freenect2Impl] 6 usb devices connected
[Info] [Freenect2Impl] found valid Kinect v2 @1:16 with serial 020354743547
[Info] [Freenect2Impl] found 1 devices
[Error] [OpenGLDepthPacketProcessorImpl] GLFW error 65544 X11: The DISPLAY environment variable is missing
[Error] [OpenGLDepthPacketProcessor] Failed to initialize GLFW.

If I connect tk1 using remote desktop, and input ./bin/Protonect, it tells me following errors

[Info] [Freenect2Impl] enumerating devices...
[Info] [Freenect2Impl] 6 usb devices connected
[Info] [Freenect2Impl] found valid Kinect v2 @1:16 with serial 020354743547
[Info] [Freenect2Impl] found 1 devices
X Error of failed request: BadRequest (invalid request code or no such operation)
Major opcode of failed request 149(RANDR)
Minor opcode of failed request 8 (RRGetScreenResources)
Serial number of failed request: 14
Currenr serial number in output stream: 14

**Comment by zinkcious** [comment]
时间太久忘记了，设备也不在了

**Comment by wuguangbin1230** [comment]
好的，谢谢了！

发自我的 iPhone

在 2018年3月9日，下午3:54，zinkcious <notifications@github.com<mailto:notifications@github.com>> 写道：


时间太久忘记了，设备也不在了
